apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: localhost:5000/python:v1
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 4
              memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  selector:
    app: python-app
  ports:
    - port: 8000
      targetPort: 8000
