apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-app
  template:
    metadata:
      labels:
        app: rust-app
    spec:
      containers:
        - name: rust-app
          image: localhost:5000/rust:v3
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 4
              memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rust-service
spec:
  selector:
    app: rust-app
  ports:
    - port: 8081
      targetPort: 8081
